services:
  api:
    build:
      context: ./api
    depends_on:
      proxy:
        condition: service_started
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - sockets:/tmp
  proxy:
    build:
      context: ./proxy
    depends_on:
      processes:
        condition: service_completed_successfully
    volumes:
      - sockets:/tmp
      - bin:/shared/bin
  processes:
    build:
      context: ./processes
    volumes:
      - bin:/shared/bin
    entrypoint: ["true"]
volumes:
  sockets:
  bin:
