[package]
name = "argparse"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.2"
serde_json = "1.0.145"
serde = { version = "1", features = ["derive"] }

[profile.release]
opt-level = 3
strip = true
